name: Deploy application to environments

on:
  workflow_call:
    
jobs: 
  build:
    name: Build
    permissions:
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environments
        run: |
          echo "Start build application"
      
      - name: Checkout on [release]
        uses: actions/checkout@v4

      - name: Comment about build application 
        uses: actions/github-script@v6
        with:
          script: |
            try {
              if (context.issue && context.issue.number) {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'Сборка проекта пройдена успешно. Сформирован релиз.'
                });
                console.log('Added build success comment to issue/PR #' + context.issue.number);
              } else {
                console.log('No issue or PR number found in context. Skipping comment creation.');
              }
            } catch (error) {
              console.error('Error creating comment:', error.message);
            }
