name: Docker push

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string 
            release_branch:
                required: true
                type: string
        secrets:
            dockerhub_token:
                required: true
            dockerhub_login:
                required: true 

env:
    REPO_NAME: ${{ github.event.repository.name }}
    CONTAINER_NAME: land_devops_1
    LABEL_DOCKER: dockerhub

jobs:
    docker-push:
        name: (CI) Docker push
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
            id-token: write
        runs-on: ubuntu-latest            
        steps:
        -   name: Prepare env 
            run: | 
                echo "show variables"
                echo [${{ inputs.tag }}]
        -   name: Checkout on [${{ inputs.release_branch }}] and v [${{ inputs.tag }}]
            uses: actions/checkout@v4

        -   name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_LOGIN }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Build and push Docker image to DockerHub
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_LOGIN }}/${{ env.REPO_NAME }}:v${{ inputs.tag }}

        # update info about docker Readme file and description
        -   name: Docker Hub Description
            uses: peter-evans/dockerhub-description@v4
            with:
                username: ${{ secrets.DOCKERHUB_LOGIN }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                repository: ${{ secrets.DOCKERHUB_LOGIN }}/${{ env.CONTAINER_NAME }}
                short-description: ${{ github.event.repository.description }}
                readme-filepath: ./README.md
                enable-url-completion: true
        
        # add label to PR 
        -   uses: actions/github-script@v7
            with:
                script: |
                    try {
                        if (context.issue && context.issue.number) {
                            github.rest.issues.addLabels({
                                issue_number: context.issue.number,
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                labels: ['dockerhub','${{ inputs.tag }}']
                            });
                            console.log('Added dockerhub labels to issue/PR #' + context.issue.number);
                        } else {
                            console.log('No issue or PR number found in context. Skipping label addition.');
                        }
                    } catch (error) {
                        console.error('Error adding label:', error.message);
                    }

        -   name: Change label
            uses: actions/github-script@v7
            with:
                script: |
                    try {
                        if (context.issue && context.issue.number) {
                            github.rest.issues.addLabels({
                                issue_number: context.issue.number,
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                labels: ['changelog-${{ env.LABEL_DOCKER }}']
                            });
                            console.log('Added changelog label to issue/PR #' + context.issue.number);
                        } else {
                            console.log('No issue or PR number found in context. Skipping label addition.');
                        }
                    } catch (error) {
                        console.error('Error adding label:', error.message);
                    }
